### ISSUE TITLE
"Any person in a leadership position..."

### ISSUE THREAD

**Issue by wseltzer** [w3c/PWETF#100]
I'm not clear what this paragraph is trying to do, and some potential readings are troublesome.
> Any person in a leadership position should provide immediate assistance to any participant who wants to contact an ombuds. Failure to do so may increase the harmful consequences of the action being reported.

Can we remove it? I think that the paragraphs before and after make clear the opportunities to contact an Ombuds directly or through speaking with those in leadership roles.

**Comment by TzviyaSiegman** [comment]
@jeffjaffe revised the [Reporting](https://w3c.github.io/PWETF/#Reporting) section. This paragraph has been replaced. It now reads

> If you are responsible for a community within the W3C such as in the role of a chair of a working group and you witness harassment or any other behavior which goes against this code you are encouraged to address the issue directly. If you need assistance, you might get assistance from an Ombudsperson or senior W3C management. 

If you are comfortable with this language, please close this issue. Thank you

**Comment by jeffjaffe** [comment]
LGTM.
