### ISSUE TITLE
Clarify physical contact being unacceptable

### ISSUE THREAD

**Issue by fantasai** [w3c/PWETF#119]
Current CEPC draft says

“Physical contact and simulated physical contact (e.g., textual descriptions like “hug” or “backrub”) without consent or after a request to stop.”

One of the branches in this sentence is “Physical contact and simulated physical contact (e.g., textual descriptions like “hug” or “backrub”) without consent.” However, greetings in the Western and Middle Eastern world often involve physical contact, and there is no clear "pre-consent" for initiating that, so the CEPC seems to disallow such very typical behavior. We could officially switch to Japanese greeting practices, but I think it would be hard to get traction on that W3C-wide, so many groups would be in constant violation of the CEPC under the current wording...

Suggestion is to follow the precedent of the earlier bullet points and prepend “Unwelcome or unprofessional” to the beginning of the sentence, something like

> Unwelcome or unprofessional physical contact or simulated physical contact (e.g. textual descriptions like “cuddles” or “backrub”), particularly after a request to stop.

**Comment by TzviyaSiegman** [comment]
Thanks @fantasai. The intent here is that even though in some cultures this is perfectly acceptable, in other cultures it is not. The phrase "without consent" intends to convey that. How is one to know if a hug is welcome without requesting consent? (I realize this seems counter to certain cultures, but we are attempting to help people work across cultures.)

**Comment by vlevantovsky** [comment]
My take on what @fantasai pointed out is that for many cultures, where physical contact as part of the greetings is acceptable and even expected, the _consent_ can simply be expressed in a body language - an extended hand in response to a handshake offer, open hands ready to accept a hug as a greeting, ... it is most likely that body language would never be truly considered as a formal consent, and such a contact may be perceived by others as a violation of the CEPC. Thus, preceding the statement with a clarifying "unwelcome physical contact" solves the concerns.

**Comment by TzviyaSiegman** [comment]
CG concluded existing text is acceptable in 3/3 meeting #124
