### ISSUE TITLE
Fix day of week and time of recurring PWETF meeting

### ISSUE THREAD

**Issue by tripu** [w3c/PWETF#12]
Proposal:

* once a month,
* on a Thursday,
* at 15:00 [UTC](https://www.timeanddate.com/time/aboututc.html) (ie, _linked_ to UTC, _fixed_ to that standard time)

Please reply :-1: or :+1: (and feel free to comment also with your preferences)

**Comment by swickr** [comment]
"at 15:00 UTC" means "fixed at 1500 UTC"; i.e. those whose local clocks adjust for "summer time" will experience a change twice a year.

**Comment by TzviyaSiegman** [comment]
This will work for me as long as it does not conflict with AB meetings (which are at the same time when we change the clocks, I think). I will work out with @lianqi how to avoid overlap.

**Comment by swickr** [comment]
@TzviyaSiegman The previous AB chose to keep its meeting time fixed w.r.t. UTC also; you might not have conflicts if the current AB keeps the schedule posted on its [home page](https://www.w3.org/Member/Board/).

**Comment by TzviyaSiegman** [comment]
This is managed via Doodle polls on an ongoing basis
