### ISSUE TITLE
semicolon use

### ISSUE THREAD

**Issue by fantasai** [w3c/PWETF#120]
> Offensive comments related to gender, gender identity and gender expression, sexual orientation, disability; both visible and invisible, mental health, neurotype, physical appearance, body, age, race, socio-economic status, ethnicity, nationality, language, or religion 

Semicolons generally are a higher-priority operator compared to a comma, so using one with the intention of it being internal to a comma-separated list's list item is weird and confusing. Suggest using parentheses

> Offensive comments related to gender, gender identity and gender expression, sexual orientation, disability (both visible and invisible), mental health, neurotype, physical appearance, body, age, race, socio-economic status, ethnicity, nationality, language, or religion 

Alternately, use a semicolon-separated list, with internal commas. https://www.grammarly.com/blog/semicolon/

**Comment by TzviyaSiegman** [comment]
fixed with #123
