### ISSUE TITLE
links to ombudsperson/ombudspeople should lead to information on who the ombudspeople are

### ISSUE THREAD

**Issue by dbaron** [w3c/PWETF#126]
The current draft (excluding the glossary) has 5 mentions of the term "ombudsperson" or "ombudspeople", all of which are links.  The first two of them are in [§ 4. Reporting Violations and Supporting the Code](https://w3c.github.io/PWETF/#Reporting), the next two are in [§ 4.2 After the meeting](https://w3c.github.io/PWETF/#after-the-meeting), and the last is in [§ 5. If you've done something improper](https://w3c.github.io/PWETF/#mistake).

For the first two mentions, the target of the link is a `mailto` link to send an email to a group of people, without any information about who those people are.  (This was somewhat surprising to me, and was the initial issue that led me to think it was worth filing an issue.)  Linking straight to a `mailto` link without any information as to who is being emailed seems like it might not help make people sufficiently confident to send emails that probably ought to be sent, because they don't understand who is going to see the email that they're writing.

For the latter three mentions, the target is [a definition in the glossary](https://w3c.github.io/PWETF/#dfn-ombudsperson).

When I clicked on the link, I was expecting the link to point to something like [this list of who the ombudspeople are and how to reach them](https://www.w3.org/Consortium/pwe/#ombuds).  I think linking to that or something like it would be more helpful in encouraging people to contact the ombudspeople when needed.

I admit there's a tension between the desire to provide good definition of "ombudsperson" and providing a quicker path to get to the list of who the people are and how to contact them, but I think it would probably be good if:
* all 5 links pointed to the same place
* the place linked to made it easy to find out what (generally) an ombudsperson is, who (specifically) the ombudspeople are, and how to contact them

One way to do this might be to drop the glossary entry, move its wording into the description above the existing list, and link only to that list.  Another way would be to have an extra level of indirection through the glossary entry.  There are probably others.

**Comment by TzviyaSiegman** [comment]
Thanks @dbaron. This is a side effect of two things. 1/ auto linking from ReSpec to gloassary terms, and 2/ PWE has just begun work on [Procedures](https://www.w3.org/Consortium/pwe/#Procedures), which includes revamping the ombudsperson program. I think that you are correct though, and it will be frustrating to reach a definition of ombudsperson. I will edit the links to reach the current version of Procedures. Thank you

**Comment by TzviyaSiegman** [comment]
@dbaron please confirm that you are OK with closing this issue. Thank you

**Comment by dbaron** [comment]
It seems like this is mostly fixed, but I think one link is still problematic.  In particular, the link closest to the end of [§ 4. Reporting Violations and Supporting the Code](https://w3c.github.io/PWETF/#Reporting):

>  If you need assistance, you might get assistance from an [Ombudsperson](mailto:ombuds@w3.org) or senior W3C management.

still links straight to a `mailto` link.

Given the links in the previous paragraph, I think it would be fine not being a link at all.  Alternatively, it could link to the glossary.
