### ISSUE TITLE
Parsing of last four bullets of Unacceptable Behavior section

### ISSUE THREAD

**Issue by GarthConboy** [w3c/PWETF#128]
Seems like an excellent document to me; clearly a lot of time when in; congratulations on publication.

I did have to read the bottom of the "Unacceptable Behavior" section a number of times until I was able to parse it correctly -- even though there is an introductory sentence, it took awhile for me to get the transition from the "don't"s to the "we'll generally overlook"s.  Maybe it could be more clear with something like "To avoid the above bullets, we will not focus on the below ones", or maybe even make it another section akin to "Not unacceptable."

**Comment by TzviyaSiegman** [comment]
Thanks @GarthConboy. There was extensive discussion about how to word this section. See #115 #117  and #121. Do you think a sub-heading would make this section clearer?

**Comment by GarthConboy** [comment]
Yes, I do think a sub-head would help a lot!
