### ISSUE TITLE
Replicate the text of the current CEPC

### ISSUE THREAD

**Issue by swickr** [w3c/PWETF#14]
Let's start with the text of the current (2015-10-05) [Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/) and create issues based on that starting text.

**Comment by swickr** [comment]
Raw content copy is now incorporated into [index.html](https://github.com/w3c/PWETF/blob/master/index.html).  The incongruities with respec markup probably should be fixed by someone who knows respec better than I.

**Comment by npdoty** [comment]
PR #22 uses ReSpec's preferred `<dfn>`, `<a>` and `<section>` headers and resolves the open warnings.

**Comment by TzviyaSiegman** [comment]
Completed.
