### ISSUE TITLE
Can this be be a living document?

### ISSUE THREAD

**Issue by tripu** [w3c/PWETF#15]
There are advantages to having it being continuously revised.
Perhaps not possible, mainly for legal reasons.
Thoughts?

**Comment by TzviyaSiegman** [comment]
I hesitate to make CEPC a living document since it is a legal document. When the AB discussed living (evergreen) standards, we pointed to documents that are also used as legal documents or referred to in legislation as examples of those that would be bad choices for living standards.

**Comment by tripu** [comment]
Even if the CEPC is a &ldquo;legal&rdquo; document, how would that be an issue, exactly?

There would always be accurate trace of what changes were introduced to the document, when, and by whom&nbsp;&mdash;&nbsp;and of what the entire text read at any point in time. Any dispute could be resolved using that information.

If the document were instead updated less often, in batches, say once a year or so&nbsp;&mdash;&nbsp;we would still be in the same situation in the future: if some conflict occurred, we would have to dig the history of the document to find out what it said exactly at the time the problem started or unfolded&hellip;

**Comment by tripu** [comment]
(@TzviyaSiegman, @wseltzer: can you ellaborate?)

**Comment by chaals** [comment]
I think we want a relatively static document with formal republication if necessary. Not just because this could be a legal document, but also because people will read it at random times and should be able to recall what was there, and not find it might have changed while they wren't watching, unannounced.

**Comment by TzviyaSiegman** [comment]
agreed on 2019-12-05 call to make this a stable document
