### ISSUE TITLE
Add "Gaming of the W3C Process" to Unacceptable Behavior

### ISSUE THREAD

**Issue by msporny** [w3c/PWETF#154]
There are a very small number of people at W3C that are expert at gaming the W3C Process. Examples include:

* Waiting until right before CR/PR and filing 20-40 new issues.
* Threatening formal objections without proposing concrete alternatives on a regular basis.
* Filing issues that are duplicates of others over a long period of time.
* Filing issues and not suggesting what changes they would like to see, or not suggesting concrete specification text after weeks of discussion on an issue (after multiple attempts at spec text changes have been made).

These are issues where doing each one of these things once or twice or more isn't an issue, but becomes an issue when it becomes repeated behavior.

**Comment by nigelmegitt** [comment]
@msporny are you thinking this is something to be added to the CEPC?

I'm not sure this is right for the CEPC, but it surely is the kind of thing that affects the positivity of the work environment, in a "prevents making good progress" kind of way. I don't think that's been the main focus of the PWETF up to now though.

The behaviour described in the issue can be problematic but it is not necessarily any kind of personal attack; it's just as likely to be a feature of time pressure or the desire for an organisation to act tactically to try to influence the progress of particular specifications. It can be annoying but it is part of the territory of working in a standards organisation, like it or not.

I _would_ like to see some definition of what a "well formed" issue or objection is. Perhaps it is something for the Guide? (I'm not sure this repo is the right place for Guide issues) In my view, a well formed objection should include a clear statement of the problem, a rationale for the objection and at least one proposal for a way to reach resolution. Issues can be looser, since they are often used for activity tracking, or to initiate conversations.

I have a problem with categorising "filing issues just before the deadline" as problematic. It does create challenges for everyone, but the deadline is the deadline. Before deadline => OK, after deadline => not OK. It is extremely unfair on people if a deadline is issued, and work is done within it, but then folk complain "oh you did it really late". Time management is a huge headache for a lot of people and this kind of thing only makes it worse. If the deadline is set too late, don't blame the people who took it on good faith. If there are repeat "offenders" then more collaborative working approaches might be needed.

**Comment by msporny** [comment]
> @msporny are you thinking this is something to be added to the CEPC?

Yes, because the end result is that it creates a toxic work environment. It allows the bad behavior of one individual/organization to affect an entire group. It has negative effects on the people doing the work and can be used as an asymmetric attack against a WG.

I have lived through two of such attacks on two different WGs... fundamentally, a large company decided that the work being done in the WG was not aligned with their corporate direction and rather than join the WG and attempt to change the work, the company instead decided to game the W3C Process, from charter review to WG formation to then doing/saying nothing for months right up until we went into CR/PR.

I have also been financially threatened (threat of lawsuit -- "there are a lot of patents in this space that our company owns, we know you don't have any in this area, it would be a terrible thing for you to misstep and find yourself at the end of a patent lawsuit"), had my business threatened, by two of these large organizations... all in hallway discussions, none of which I could prove by the same organizations that did the above.

These behaviors are Unethical and the conduct is not professional. I don't know where else we would call these things out if not in the Code of Ethics and Professional Conduct.

I do think you have valid concerns about where to draw the line, and I agree that this isn't as night and day as my opening remark... but it does become an issue when the behavior is repeated -- that is, evidence mounts until it's clear that something is wrong.

I've certainly stepped back as the face of a number of initiatives because of the toxicity of this sort of behavior and becoming a target on more than one occasion.

**Comment by msporny** [comment]
> and perhaps we should discuss this in a private space

I'm happy to discuss this openly... part of the problem is that these things don't get discussed openly.

> I am interested to know if you think the CEPC is sufficient.

In those particular cases it wasn't, not really. It took extraordinary effort by the target of those attacks to get anything done, in both cases the matter was resolved not because people were held accountable, but because the people left W3C (and continued doing what they were doing at W3C in other venues).

The CEPC won't ever be 100% effective, but it does help establish the community contract. Contracts can be made more effective when they are announced and enforced... it's the announcement and enforcement part that's a bit lacking presently.

**Comment by mnot** [comment]
The problem is that this is attempting to capture bad-faith behaviour, and that's always in the eye of the beholder.

**Comment by msporny** [comment]
> The problem is that this is attempting to capture bad-faith behaviour, and that's always in the eye of the beholder.

Sure, slippery slope... but what happens when the behavior is observed by multiple parties, and acknowledged as bad-faith behavior by multiple parties (including Chairs of a WG and individuals that were a part of PWETF)? There are people that know the process well enough to game it, and do (on occasion)... and the CEPC might not say enough about that.

To draw an imperfect analogy, there are laws and the vast majority of people stay well within those boundaries (law abiding citizens). There are those that blow right pass the boundaries (criminals). Then there are those that skirt the boundaries in a way that has a positive impact on society (society benefits)... and those that skirt/cross the boundaries for personal gain, that have a negative impact on society (society bears the cost). It's this last group with which this issue is concerned.

The problem with "presume good faith" (which I agree with as a general principle) is that it also empowers bad actors to game systems. That is what enables individuals to game systems in a way that has a negative impact on society. At some point, individuals do act in bad faith (the CEPC lists examples of those behaviors).

I don't know the best way to express this in CEPC, and perhaps you're right... maybe it is better left unsaid... or maybe it is more broadly covered in the existing document. It's been a while since I did a full read through of the CEPC.

All this said, if PWETF feels that this item is covered, they should feel free to close this issue.

**Comment by dbooth-boston** [comment]
Perhaps "nine strikes and you're out" for bad-faith behavior, using a lower burden of proof, like "preponderance of evidence" instead of "beyond a reasonable doubt"?

**Comment by TzviyaSiegman** [comment]
Thanks for the comments @mnot and @msporny. As before, I feel that this falls under "deliberate intimidation" or "sustained disruption of discussion".  This isn't so much about assuming good faith or bad faith, both of which can be problematic in different scenarios.  This is about leaving judgment to ombuds/mediators.

**Comment by mnot** [comment]
I agree that the behaviour that's concerning @msporny can be covered under existing characterisations.

What I'm concerned about is the ability to cast behaviour that is explicitly allowed by the Process as a CEPC violation, and the judgement of that violation boiling down to some people saying 'yes, that's what it feels like.'

That's a recipe for excluding people who have positions which aren't widely held in the group -- especially when the group has a desire to avoid conflict.

**Comment by wareid** [comment]
As Tzviya said, this falls to the judgement of the ombuds and mediators should it come to that. "Deliberate Intimidation" and "Sustained disruption of discussion" are both well defined and have high bars to clear. Someone taking a contrary position on an issue and defending that position in calls or email is not either of those. Someone holding a contrary position and pushing it past the point where a group has reached consensus to the degree it is disruptive is another matter. I don't think we need additional language in regards to process specifically.

**Comment by msporny** [comment]
@TzviyaSiegman wrote:
> As before, I feel that this falls under "deliberate intimidation" or "sustained disruption of discussion". This isn't so much about assuming good faith or bad faith, both of which can be problematic in different scenarios. This is about leaving judgment to ombuds/mediators.

@mnot wrote:
> I agree that the behaviour that's concerning @msporny can be covered under existing characterisations.

@wareid wrote:
> As Tzviya said, this falls to the judgement of the ombuds and mediators should it come to that... I don't think we need additional language in regards to process specifically.

Looks like we have consensus for those engaging in the discussion. I'm satisfied that PWETF has thought about the issue and has come to a conclusion that additional language is not necessary. Thank you all for your time and consideration. 

Closing, as I'm the submitter of the issue and am satisfied with the outcome.
