### ISSUE TITLE
Does CEPC apply to CGs?

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/PWETF#16]
I was asked if [CEPC](https://www.w3.org/Consortium/cepc/) applies to community groups. If so, can we automatically link to it on CG pages in the same way that we link to the CLA?

@tripu @wseltzer

**Comment by tripu** [comment]
I see a link &ldquo;Contributor License Agreement (CLA)&rdquo; on [`https://www.w3.org/community/about/`](https://www.w3.org/community/about/).

Is that where you would want to add a link to the CEPC too?

**Comment by TzviyaSiegman** [comment]
@tripu yes, if the CEPC applies to CGs, we should post it with the CLA.

**Comment by wseltzer** [comment]
Yes, the Code covers CGs by its terms: "This code (CEPC), complemented by a set of Procedures, applies to any member of the W3C community – staff, members, invited experts, participants in W3C meetings, W3C teleconferences, W3C mailing lists, W3C conference or W3C functions, etc" 

I agree we should link it under "Policies" in the about CGs page.

**Comment by TzviyaSiegman** [comment]
Thanks. @tripu can we make this change?

**Comment by wseltzer** [comment]
Done!

**Comment by tripu** [comment]
@wseltzer, did you just edit the WordPress menu &ldquo;Policies&rdquo;?
I now see that menu repeated at the top of the page on [`w3.org/community/about`](https://www.w3.org/community/about/) (with bad positioning and style), and it seems to be &ldquo;primary navigation&rdquo; now&hellip;

**Comment by wseltzer** [comment]
thanks @tripu, I think I fixed that
