### ISSUE TITLE
Example Russian CoC

### ISSUE THREAD

**Issue by thisisjofrank** [w3c/PWETF#18]
[Правила поведения на FrontTalks.pdf](https://github.com/w3c/PWETF/files/2510404/FrontTalks.pdf)

Used at multiple Russian dev evnts

Also https://2019.codefest.ru/speakers/en/code-of-conduct/ - code of conduct for a large web event run in Novosibirsk, Russia.

**Comment by TzviyaSiegman** [comment]
Thanks @thisisjofrank. I am having trouble accessing the one in PDF format. Do you have another pointer?

**Comment by thisisjofrank** [comment]
Ah sorry! Think work laptop encrypted it. Maybe this one will work.
[Правила поведения на FrontTalks.pdf](https://github.com/w3c/PWETF/files/2529265/FrontTalks.pdf)

**Comment by thisisjofrank** [comment]
Ah, i think my machine encrypted it. Try this one? https://drive.google.com/file/d/1CyTAD7SxqREd1v30cs8Yyl84QrAh4muf/view?usp=sharing

**Comment by TzviyaSiegman** [comment]
Thank you!

**Comment by TzviyaSiegman** [comment]
Thanks! I've added this to [References and Resources](https://github.com/w3c/PWETF/blob/master/ReferencesAndResources.md).
