### ISSUE TITLE
Disinformation as unacceptable behaviour

### ISSUE THREAD

**Issue by csarven** [w3c/PWETF#200]
I could not find detailed discussion or documentation on unacceptable behaviour pertaining to disinformation and was hoping to get some pointers to prior coverage.

I suppose my initial question is whether it is already adequately covered by the current CEPC.

I believe it may be as per CEPC's [Expected Behaviour](https://www.w3.org/Consortium/cepc/#expected-behavior):

>Be honest. Be truthful, sincere, forthright and, unless professional duties require confidentiality or special discretion, candid, straightforward, and frank.

But if there is some other text that I've missed either in CEPC or elsewhere that covers disinformation, it'd be very insightful. If CEPC is already covering this, I'm satisfied, and this issue can be closed.

(IMO, having it under "Expected Behaviour", as it is currently, as a way to encourage positive behaviour comes across better than calling out the negative as an "Unacceptable Behaviour". If my interpretation is correct, thank you for doing that. :))

**Comment by csarven** [comment]
Aside: I appreciate this statement from [Cognitive Accessibility Roadmap and Gap Analysis](https://www.w3.org/TR/coga-gap-analysis/#introduction):

"Attitudes and misinformation can also become a barrier to inclusion for people with cognitive disabilities."

**Comment by TzviyaSiegman** [comment]
Thanks @csarven. We will consider for a future draft.

**Comment by TzviyaSiegman** [comment]
fixed by #201
