### ISSUE TITLE
[CEPC] Add text discouraging the use of violent imagery

### ISSUE THREAD

**Issue by hober** [w3c/PWETF#21]
The CEPC should discourage W3C participants from the use of violent imagery in presentation materials, including (photographic or artistic) depictions of personal and/or mass violence, e.g. the aftermath of well-known mass casualty events.

(Edited to clarify context where this came up in standards work.)

**Comment by TzviyaSiegman** [comment]
Thanks @hober. I agree with the idea, but I am a little unclear about where this fits into the world of standards. Is the concern about behavior on social media and similar? If you prefer to discuss privately, please in touch.

**Comment by hober** [comment]
> Thanks @hober. I agree with the idea, but I am a little unclear about where this fits into the world of standards.

Does the above edit (addition of "in presentation materials") clarify things?

**Comment by TzviyaSiegman** [comment]
Thanks for the edit. Much clearer.

**Comment by wseltzer** [comment]
I wonder if a good first place to add such guidance is in an update to the [speaker resources wiki](https://www.w3.org/wiki/Speaker_Resources) and then link that more prominently from calls for presentations.

**Comment by wseltzer** [comment]
Added to https://www.w3.org/wiki/Speaker_Resources#About_Slides_Specifically.E2.80.A6

**Comment by TzviyaSiegman** [comment]
Thanks @wseltzer. @hober if you're comfortable with this resolution, please close the issue.
