### ISSUE TITLE
CEPC lacks a code of ethics

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/PWETF#223]
Thanks for your work on this document!  https://www.w3.org/Consortium/cepc/cepc-20200716/
But I do have a few suggestions, which I'll post in separate issues, to facilitate tracking.

The document title is says it is a "Code of Ethics and Professional Conduct", but the content of the document only addresses professional conduct.  It completely omits professional ethics --  conflict of interest, etc.  I suggest either dropping the word "ethics" from the title, or adding a major section on professional ethics (including conflict of interest).

**Comment by TzviyaSiegman** [comment]
Discussed in PWE 2023-01-17. Will revisit in 2 weeks

**Comment by dbooth-boston** [comment]
> Discussed in PWE 2023-01-17. Will revisit in 2 weeks

Is there a link to the minutes?

**Comment by TzviyaSiegman** [comment]
https://www.w3.org/2023/01/17-pwe-minutes.html

**Comment by dbooth-boston** [comment]
Discussed and resolved [on today's call](https://www.w3.org/2023/01/31-pwe-minutes.html):

> RESOLUTION: Change name of CEPC to Code of Professional Conduct (CPC)

I think this issue can be closed.
