### ISSUE TITLE
CEPC: Assume that the audience is "intelligent but uninformed"

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/PWETF#225]
Version reviewed: https://www.w3.org/Consortium/cepc/cepc-20200716/

In section 3.2 (Unacceptable behavior), this bit of guidance I believe is overstated to the point of being harmful:

> Assuming without asking that particular people or groups need concepts defined or explained to them. It’s great to be sensitive to the fact that people may not be familiar with technical terms you use every day, but assuming that people are uninformed can come across as patronizing. 

Based on my own experience of 30+ years of presentations in Computer Science, I would say that that guidance is exactly wrong.  If you are not CERTAIN that your audience already knows your jargon and the context of your presentation, you should ALWAYS define your terms and clearly set the context.   Failing to do so unnecessarily obscures your message and creates an environment in which an "in crowd" knows your jargon and context, and all others are excluded.  That is the OPPOSITE of what we should be trying to do.

Certainly if the WHOLE audience already knows your jargon and the context of your topic, then it would be pointless to waste their time by reviewing it.  But in over 30 years, I have VERY rarely seen that happen.  On the other hand, the opposite happens FREQUENTLY: a speaker does not define terms, and many in the audience are lost but afraid to speak up.  That is harmful and counterproductive.

Furthermore, in my experience it does not work well to ask the audience if they are already familiar with your jargon.  Usually they either assume that they are -- even if they're wrong -- or they are afraid to sound ignorant by admitting that they aren't.  Either way, it works MUCH better to simply be inclusive from the start, by defining your terms and setting the context.

The golden guidance I learned from one of my esteemed professors years ago was to assume that the audience is "intelligent but uninformed".  I think he nailed it.

I suggest changing the above-reference paragraph to something along these lines:

> Do not make assumptions about people's knowledge or skill based on their physical appearance, gender identity or other irrelevant characteristics.

**Comment by cwilso** [comment]
I think you may be missing a key part of that statement - "assuming without asking that _particular_people_ or groups need concepts defined" is poor practice, because you are identifying a particular group as uninformed.  Defining your terms, jargon, context, etc. ALWAYS is not offensive; it's just being cautious.  Only defining your terms when speaking in one audience but not another might be offensive, though.

**Comment by dbooth-boston** [comment]
I certainly agree with the intent, but I don't think the current prose clearly enough meets that intent, and I think it contains some harmful implicit advice.  I think the prose should be clarified in four specific ways:

1. The document should clarify that when it refers to "particular people or groups", it is talking about people or groups _based on their physical appearance, national origin, gender identity or other irrelevant characteristics_.  It is NOT talking about people or groups based on _relevant_ characteristics, such as prior work on the topic, or other known background on the topic.  It is okay (and helpful) to distinguish groups based on _relevant_ knowledge of the audience's background.
2. The document should not imply that it is okay to ask the audience if they are familiar with one's jargon.  That approach doesn't work. 
3. The document should not imply that defining one's jargon is a sign of disrespect.  That is a harmful message to convey, because it will discourage people from defining their jargon and context.  Defining one's jargon and context helps to create a more INCLUSIVE environment.  Sometimes (though rarely) it is okay to skip it, but only based on _relevant_ knowledge of the audience's background -- not on irrelevant things like people's appearance, gender, nationality, etc.
4. The document should avoid implying that the default is NOT to define one's jargon and context, and one only needs to define one's jargon and context for particular groups.  That is a harmful message, because the default should ALWAYS be to define one's jargon and context.

Since this is not a document on how to do effective technical presentations, I think the guidance can be simplified down to something along the lines suggested at the beginning of this thread, though others might come up with better wording.

**Comment by dbooth-boston** [comment]
This issue is subsumed by https://github.com/w3c/PWETF/issues/232 .

**Comment by dbooth-boston** [comment]
Closing this issue, because it is subsumed by #232 .
