### ISSUE TITLE
CEPC: Safety versus comfort

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/PWETF#228]
Version reviewed: https://www.w3.org/Consortium/cepc/cepc-20200716/

Section 3.2.1 discusses "Safety versus Comfort".  I agree with prioritizing the safety of marginalized individuals over the comfort of others, but in reading the section, it is not clear to me what guidance is intended.   It includes these examples:

>  "Reverse" -isms, including "reverse racism," "reverse [sexism](https://www.w3.org/Consortium/cepc/cepc-20200716/#dfn-sexism)," and "cisphobia".

I personally find the term "reverse racism" offensive (both because it denies the historic impact of "forward racism", and because it implies that historic racism is "forward"), so that may interfere with my ability to understand the point of this example.   But it feels like it lacks a verb.  Is it trying to say that "reverse racism" is unacceptable?  Or that the negative impact of (historically "forward"?) racism" takes precedence over "reverse racism"?  If so, I think it would help to state that explicitly.

>  Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you”.

I personally would be rather shocked if I tried to ask someone a technical question and the person responded "Go away" or "I'm not discussing this with you".  I would NOT consider that a "reasonable communication of boundaries" in any sense.  I would consider that quite anti-social behavior that is NOT conducive to building an inclusive and welcoming work environment.  So I don't know exactly what guidance is intended by this example, but whatever it is, I think should be clarified.

>  Communication in a tone you don’t find congenial.

Again, I think a non-congenial tone is not conducive to building an welcoming work environment, and over time, can even constitute harassment (micro aggressions).  So again, it isn't clear to me what guidance is intended.

>  Criticisms of racist, sexist, [cissexist](https://www.w3.org/Consortium/cepc/cepc-20200716/#dfn-cissexist), or otherwise oppressive behavior or assumptions."

To my mind, racism, sexism and oppressive behaviors should not be tolerated.  But again it isn't clear to me what guidance this example intends to be giving.  Is it trying to say that speaking out against racism, sexism and oppressive behaviors might make  some people uncomfortable, but that discomfort is less important than speaking out against such harms?  If so, I think it would be helpful to say so explicitly.  If not, please tell me what guidance is intended by that example, because I find it unclear.

P.S. Thank you again to everyone who has put so much effort into drafting this document!

**Comment by TzviyaSiegman** [comment]
Please see https://github.com/w3c/PWETF/issues/121 for previous discussion

**Comment by TzviyaSiegman** [comment]
Please also note that Safety Versus Comfort is a subsection of Unacceptable Behavior. Previous sections have already made it clear that racism, sexism, etc are not acceptable. This section prohibits "reverse racism" etc. We put the reverse -isms in quotes to indicate that these are false concepts. An earlier draft included a definition, but as you'll see in #121  we felt that validated the concept. 

Regarding the other points, when we are addressing an issue of safety, we have left the realm of technical conversation. We are dealing with a person at risk. It is irrelevant whether this feels antisocial. Saying, "Go away!" to an aggressor, or "I'm not discussing this with you." to someone using sexual innuendo is perfectly fine. If we explain this in too much detail it leaves room for an offender to tell us that they were not really in violation of the code; rather the person who said "Go away" was being antisocial.

**Comment by dbooth-boston** [comment]
Please don't close this issue yet.  AFAICT the concerns that I raised have not yet been addressed.

I'd also like to suggest in general, that before closing an issue: a. check with the person who raised the issue, to see if the commenter is okay with the proposed resolution; and b. document the rationale for the decision.  I think both of these are best practices for consensus-driven groups.

When I raised this issue, I was unable to make specific improvement suggestions because I did not have a clear understanding of the intent of the section.  I *think* I now have a better understanding of the intent, but not fully.

> when we are addressing an issue of safety, we have left the realm of technical conversation. We are dealing with a person at risk. It is irrelevant whether this feels antisocial. Saying, "Go away!" to an aggressor, or "I'm not discussing this with you." to someone using sexual innuendo is perfectly fine.

Thank you!  That is *very* important contextual information that should be included in the document.  Am I now correct in understanding that the intent is that, although in a positive work environment it is not *normally* okay to respond in a non-congenial tone, or rudely like "leave me alone", “go away,” or “I’m not discussing this with you”, such a response is justifiable (as self defense) when the respondent's safety feels threatened?  If so, I think it's important to clearly state that context, to avoid in any way suggesting that it is *normally* okay for someone to respond "go away" in a PWE.

> If we explain this in too much detail it leaves room for an offender to tell us that they were not really in violation of the code

I fundamentally disagree with being intentionally vague here.  I believe that the *primary* function of this document is to educate people about acceptable vs unacceptable behavior.  Its use as an enforcement tool is secondary.  Being vague badly undermines its educational purpose.  But it also undermines its effectiveness as an enforcement tool, because it opens the Ombud to potential accusations of arbitrary and capricious enforcement.

I think a better approach is to be clear about the intent, but *also* explain that the Ombud has enforcement discretion based on the circumstances and context of any claimed transgression, both because the Ombud must consider proportionality, and because claims of so-called "reverse discrimination" and the like are usually spurious.  

Returning now to section 3.2.1, I think the overall reason I'm finding that section so confusing is that, although it is a subsection of "Unacceptable behaviors": 1. It does not clearly state what behavior is unacceptable in light of "[prioritizing] the safety of individuals . . . over the comfort of others"; and 2. based on my understanding so far, it sounds like some of the bullets in section 3.2.1 are actually intended to be read as *acceptable* behavior in some circumstances (such as when the individual's safety feels threatened), rather than unacceptable.  If examples of sometimes-acceptable behavior are listed in an overall section on unacceptable behaviors, the text should more clearly say both that they are normally *unacceptable*, and under what circumstances they are acceptable.

Regarding this bullet in section 3.2.1:

> Criticisms of racist, sexist, cissexist, or otherwise oppressive behavior or assumptions. 

To my mind, criticisms of racist or other oppressive behavior should *always* be viewed as acceptable behavior, so I don't see why that bullet is included in a list of normally *unacceptable* behaviors that are *sometimes* acceptable.

And I am still puzzled about this bullet in 3.2.1:

> "Reverse" -isms, including "reverse racism," "reverse sexism," and "cisphobia".

Is it also trying to say that "reverse racism" is sometimes acceptable?   If so, I don't think it makes sense to both say that it is sometimes acceptable and claim that it is a false concept.  If it's a false concept, then we should not be saying that it is sometimes acceptable behavior.  I suggest removing that bullet entirely, unless it is rewritten to be about *claims* of "reverse racism" and the like, rather than "situations involving" them.

I wish I could propose alternate text for this section, but I first need to find out whether I am fully understanding the group's intent here.  I'm not yet confident that I do.

**Comment by TzviyaSiegman** [comment]
We adapted this section from the Geek Feminism CoC https://geekfeminismdotorg.wordpress.com/about/code-of-conduct/. We chose not to use the phrase "We will not act on..." because we felt it was a little too firm.  It's clear that this has led to some confusion.  What if we change our code to:

> This Code prioritizes the safety of individuals, particularly those in marginalized communities, over the comfort of others. We will prioritize safety in situations such as:
> 
> - "Reverse" -isms, including "reverse racism," "reverse sexism," and "cisphobia".
> - Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you”.
> - Communication in a tone you don’t find congenial.
> - Criticisms of racist, sexist, cissexist, or otherwise oppressive behavior or assumptions.

We could also make this its own section instead of a subsection of Unacceptable Behaviors. We seem to have fundamentally different approaches to what a code of conduct should/should not include, but that is a philosophical discussion.

**Comment by dbooth-boston** [comment]
This is long because it collects lots of small and a few larger suggestions, along with explanations of my reasoning.  But I've numbered the suggestions to make them easier to manage and address.  These suggestions supersede suggestions 1, 2 and 2a that I previously made in https://github.com/w3c/PWETF/issues/226

BTW, thanks @TzviyaSiegman for the pointer to the Geek Feminism CoC, and for the idea of moving that section.  I've incorporated that idea in the suggestions below.

 --------------

SUGGESTION 3: Change the document title from 'Positive Work Environment at W3C: Code of Ethics and Professional Conduct' to 'Positive Work Environment at W3C: Code of Professional Conduct'.

EXPLANATION: The document should reflect the content, but the document does not cover ethics (such as conflict of interest, etc.), and it is already long.  It would be more effective to cover ethics in a separate document than further expanding this document.

 --------------

SUGGESTION 4: In the Abstract, change "W3C's Code of Ethics and Professional Conduct" to "This document".

EXPLANATION: Repeating the title forces the reader to wonder what document is being referenced, and then realize that it is the self-same document that the reader is reading.  Also, "This document" is shorter.

 --------------

SUGGESTION 5: In the Abstract, change "accepted and acceptable" to "acceptable".  

EXPLANATION: "accepted and" doesn't add anything.

 --------------

SUGGESTION 6: In the Abstract, Delete the "Provide a benchmark" bullet.  

EXPLANATION: 1. benchmarks are about measurement, but the document does not contain anything about measurement; and 2. it doesn't add anything.

 --------------

SUGGESTION 7: In the Abstract, move the "Ensure an environment where people can participate without fear of harassment" bullet before the "Ensure transparency in community and group management".

EXPLANATION: More important bullets should be listed before less important bullets.  

 --------------

SUGGESTION 8: In section 2 (Statement of Intent), to the end of the first sentence add: "that is safe and welcoming for all, regardless of level of experience, gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, nationality, technology choices, or other irrelevant characteristic."

EXPLANATION: This was cribbed from the WHATWG Code of Conduct https://whatwg.org/code-of-conduct and I think more clearly describes -- up front -- the intent of the document.

 --------------

SUGGESTION 9: In section 3 (Code), before section 3.1 insert a simple summary of the code, such as the following (derived from the WHATWG Code of Conduct https://whatwg.org/code-of-conduct ):

[[
This code of conduct can be summarized as follows:

 - Be kind and courteous to all.

 - Respect that people have differences of opinion and that every design or implementation choice carries a trade-off and numerous costs. There is seldom a single right answer.

 - Do not insult, demean, or harass anyone. Harassment includes, but is not limited to, offensive verbal comments or behavior related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, nationality, and technology choices; sexual images in public spaces; deliberate intimidation, stalking, doxing, following, inappropriate photography or recording; unwelcome physical contact or sexual attention; repeated interruptions, and sustained disruption of events. 

 - Be mindfully inclusive of people in socially marginalized groups, and avoid statements or behaviors that may make them feel unsafe or unwelcome -- especially trigger phrases.

The remainder of this document further articulates these expectations and provides guidance for handling violations.
]]

EXPLANATION: The document is already long.  Although it has lots of good details and examples, they all boil down to a few general principles, which would be helpful to explicitly summarize up front.  This would reinforce the purpose of the document, aid readers who do not have time to read the whole document; and help it feel less like a long laundry list of "do's" and "don'ts".

 --------------

SUGGESTION 10: In section 3.2 (Unnacceptable Behavior), in the bullet on "Microaggressions", change "Microaggressions, which are" to: "Microaggressions or microharms, which are".

EXPLANATION: This is a linguistic issue.  The current sentence includes "intentional or unintentional", but it is not possible for an aggression to be unintentional, because the word "aggression" inherently involves intent, though it certainly can be unconscious.  (If I accidentally step on someone's foot while being jostled in a crowded subway, that is not aggression, even though it can still cause harm.)  Nonetheless, words or actions can still cause harm even without conscious or unconscious harmful intent, and this is important for the document to point out.  One easy way to solve this problem would be to insert "or microharms", as suggested.  Another solution could be to re-word the sentence to separately address microaggressions vs unintended harms.

Note that this suggestion is also related to suggestion 15 below, regarding the definition of "microaggression", though this suggestion is much simpler to address.

 --------------

SUGGESTION 11: In section 3.2 (Unnacceptable Behavior), change the "Patronizing language or behavior" bullet and its three sub-bullets to the following bullets:

[[
 - Use of trigger phrases that may distress or offend certain groups or individuals.  Be aware that some terms, though neutral in their original meanings, now have offensive connotations within some groups.  For example, "thug" carries racial undertones to some.  As another example, an interjection beginning "Well, actually . . ." sounds patronizing to some, and may be taken as a sign of disrespect.

 - Patronizing language or behavior, such as assuming that particular individuals are less competent or skilled based on their appearance, nationality, gender identity or any other irrelevant characteristic.

 - Pedantic or repeated corrections that don’t contribute to the conversation. 
]]

EXPLANATION: 1. It's important to avoid suggesting that speakers should not define their jargon.  2. It is helpful to point out that trigger terms are often neutral to some, but offensive to others.  3. This clarifies that one should not make assumptions about certain groups or individuals based on *irrelevant* characteristics.  This suggestion also attempts to address this comment (which was previously neglected?), though the wording has been changed: https://github.com/w3c/PWETF/pull/46#discussion_r273520758

 --------------

SUGGESTION 12: Regarding section 3.2.1 (Safety versus comfort), move this section to become a new section 4.3, and reword it:

[[
This Code prioritizes the safety of individuals, particularly those in marginalized communities, over the comfort of others.  For example:

 - Although a curt response like "leave me alone", “go away,” or “I’m not discussing this with you” would normally be a violation of this code, such a response is justifiable (as self defense) when the respondent's safety feels threatened by an aggressor, and should be immediately respected.

 - The Ombud may not act on claims of "reverse"-isms, including "reverse racism," "reverse sexism," and "cisphobia", that arise out of reasonable efforts to correct a larger injustice.

 - Efforts to prevent or correct oppressive behavior, such as criticizing racist, sexist or cissexist behavior, are permissible even if they make other participants uncomfortable.
]]

EXPLANATION: 1. This section really seems to be about enforcement, and how Ombuds should respond to complaints, so section 4 seems like a more appropriate place for it.  2.  The "go away" example needed more contextual explanation to avoid implying that it is normally okay to respond "go away" to someone.  3. Similarly, the other examples needed a little more context.

 --------------

SUGGESTION 13: Change "Ombudsperson"/"Ombudspeople" to "Ombud"/"Ombuds" throughout.

EXPLANATION: It is simpler, less clumsy, and follows the same established pattern of shortening "Chairman"/"Chairwoman"/"Chairperson" to "Chair".

 --------------

SUGGESTION 14: In section 5 (If You've Done Something Improper), change "Improper" to "Harmful", both in the section title and the body.

EXPLANATION: "Improper" has connotations of elitism and arbitrariness: Who defines what is 'improper'?   The document should instead focus on preventing harm.

 --------------

SUGGESTION 15: In section 6 (Glossary), in the definition of Microagression, change "whether intentional or unintentional" to "whether conscious or unconscious".

Variation 15a: Or change the definition to "an indirect or subtle action or statement regarded as denigrating a minority or marginalized group", adapted from the Collins dictionary definition:
https://www.collinsdictionary.com/us/dictionary/english/microaggression

Variation 15b: Or change the definition to "everyday subtle put-downs directed towards a marginalized group which may be verbal or non-verbal and are typically automatic", from this PubMed article on microagressions:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6565651/

EXPLANATION: I am probably more sensitive to proper and logically consistent word usage than most people, but it always bothers me when words are used in ways that do not make logical sense.  The problem with including "whether intentional or unintentional" is that the word "aggression" already inherently involves intent, so it doesn't make logical sense to talk about "unintentional aggression", though it certainly makes sense to talk about "unconscious aggression".  Many definitions of "microagression" include "unintentional", but not all.  I would prefer that we avoid that logical inconsistency.

-------------

Again, thanks to all of you for all of your hard work on this document, and I hope these suggestions are helpful.

**Comment by wareid** [comment]
Closed as related issues were addressed in PRs.
