### ISSUE TITLE
W3C Ombuds list is out of date

### ISSUE THREAD

**Issue by npdoty** [w3c/PWETF#229]
https://www.w3.org/Consortium/pwe/#ombuds is the best available list I could find for who the Ombudspeople are and how to contact them. It appears to be out of date, as the CEO has changed, and MIT is no longer a formal Partner, and the other universities aren't Hosts any longer.

Also, is there a better process for making sure we keep that list up to date besides noticing and filing issues here? Maybe it's the responsibility of anyone on the Ombuds list to identify their replacement if they are leaving that role?

/cc @koalie as she's listed as owner of the HTML page

**Comment by TzviyaSiegman** [comment]
Thanks @npdoty. Very timely issue. We mentioned in our last meeting that we will begin the work of editing this page in conjunction with the new ombuds process. We have the editable page html at https://github.com/w3c/PWETF/blob/main/PWE.html. We can make incremental changes now.

**Comment by koalie** [comment]
In the meantime, I've replaced Jeff by Ralph, updated the labels to refer to regions rather than Hosts, moved Jeff to the acknowledgements.
@npdoty if that satisfies you  @TzviyaSiegman

**Comment by npdoty** [comment]
Thanks, that's much improved and I appreciate the prompt corrections! If the plan is already to further revise this document, then I don't think we need to keep this issue open.
