### ISSUE TITLE
Include an up-front overview of the code

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/PWETF#230]
This issue separates out (and supersedes) suggestion 9 from https://github.com/w3c/PWETF/issues/228 .

BACKGROUND: The CEPC document is already long. Although it has lots of good details and examples, they all boil down to a few general principles, which would be helpful to explicitly summarize up front. This would reinforce the purpose of the document, aid readers who do not have time to read the whole document; and help it feel less like a long laundry list of "do's" and "don'ts".

SUGGESTION: In section 3 (Code), before section 3.1 insert a simple overview of the code, such as the following (derived from the WHATWG Code of Conduct https://whatwg.org/code-of-conduct ):

[[
This code of conduct can be summarized as follows:

-  Be kind and courteous to all.

- Respect that people have differences of opinion and that every design or implementation choice carries a trade-off and numerous costs. There is seldom a single right answer.

- Do not insult, demean, or harass anyone. Harassment includes, but is not limited to, offensive verbal comments or behavior related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, nationality, and technology choices; sexual images in public spaces; deliberate intimidation, stalking, doxing, following, inappropriate photography or recording; unwelcome physical contact or sexual attention; repeated interruptions, and sustained disruption of events.

- Be mindfully inclusive of people in socially marginalized groups, and avoid statements or behaviors that may make them feel unsafe or unwelcome -- especially trigger phrases.

The remainder of this document further articulates these expectations and provides guidance for handling violations.
]]

In accordance with the CC-BY license, we would also need to add an acknowledgement at the end of the CEPC,  stating that portions were derived from the [WHATWG Code of Conduct](https://whatwg.org/code-of-conduct).

**Comment by TzviyaSiegman** [comment]
decided not to include an overview
