### ISSUE TITLE
Add "or microharms" or otherwise reword the Microaggressions bullet

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/PWETF#231]
This issue separates out (and supersedes) suggestion 10 from https://github.com/w3c/PWETF/issues/228 .

BACKGROUND: This is a linguistic issue. The current section 3.2 bullet on "Microaggressions" begins with this sentence:

 > Microaggressions, which are small comments or questions, either intentional or unintentional, that marginalize people by communicating hostile, derogatory, or negative beliefs.

The problem is with the phrase "intentional or unintentional" in this contexts.  It is not possible for an _aggression_ to be unintentional, because the word "aggression" inherently involves intent, though it certainly can be unconscious. (If I accidentally step on someone's foot while being jostled in a crowded subway, that is not aggression, even though it can still cause harm.) Nonetheless, words or actions can still cause harm even without aggressive intent, and this is important for the document to point out. One easy way to solve this problem would be to insert "or microharms", as suggested below. Another solution could be to re-word the sentence to separately address microaggressions vs unintended harms.

SUGGESTION: In section 3.2 (Unnacceptable Behavior), in the bullet on "Microaggressions", change "Microaggressions, which are" to: "Microaggressions or microharms, which are".

**Comment by nigelmegitt** [comment]
Aggression can be perceived even when unintended. I imagine that it's quite frequent that a perception of repeated microaggressions is exactly _because_ the aggressor does not intend them, and therefore does not recognise that they are doing them; for many such aggressors, if they were aware, they would change their behaviour.

It is worth calling out the difference between intent and perception more strongly?

**Comment by TzviyaSiegman** [comment]
Microaggressions don't need to be intended as harmful. Perhaps there is some misunderstanding? See https://hbr.org/2022/03/we-need-to-retire-the-term-microaggressions for example.

**Comment by dbooth-boston** [comment]
> Aggression can be perceived even when unintended.

Yes, an action can be _perceived_ as aggression even if it was in fact an accident (i.e., _not_ aggression).

> Microaggressions don't need to be intended as harmful. Perhaps there is some misunderstanding? See https://hbr.org/2022/03/we-need-to-retire-the-term-microaggressions for example.

My quibble is with the "aggression" part of the word, whereas that article takes issue with the "micro" part of the word -- pointing out that such harms can have major impacts.  I guess both are valid criticisms of the term.

I realize that the definition of "microaggression" currently in the document includes unintended harms.  (That's another issue.)  That definition is fairly common, but it is not universal.  But including unintended harms in the definition is self-contradictory, because the word "aggression" already inherently carries intent.  Many people don't care if terms are nonsensical or logically inconsistent, but it bothers me.  It is similar to hearing someone say "I could care less", when what they meant was the exact opposite: "I could NOT care less".  With "microaggression" the contradiction is more subtle than "I could care less", but it's still there.  I tend to be a stickler for proper word usage, so I'm well aware that I'm in the minority of English speakers, and it certainly isn't a hill I'd die on, but I always prefer to nudge wording in the direction of proper and logical word usage when possible.

All in all, I would favor focusing on _harm_ , which is really what matters, rather than _aggression_, which is slightly misguided, because many (or even most?) of the harms that the term tries to capture do not actually involve _aggression_ per se, though they can certainly _feel_ like aggression to the recipient.

**Comment by cwilso** [comment]
"Microaggressions" is, as you said, a common term.  It has a Wikipedia definition (https://en.wikipedia.org/wiki/Microaggression), which defines it the same as the CEPC - in particular, that they need not be intentional.  The definition of aggression does NOT inherently carry intent - for example, Oxford defines aggression as "hostile or violent behavior or attitudes toward another".  One's behavior can be hostile ("unfriendly; antgonistic") without it being intentional.

I don't think we should change text here; it is clear, direct, and appropriate colloquially.

**Comment by dbooth-boston** [comment]
I don't agree with your interpretation of the definition of "hostile", but I respect your opinion.   And like I said, it's not a hill I'd die on anyway.

**Comment by LJWatson** [comment]
I tend to favour the "proper" use of words, but only to the extent that it enables readable and understandable content. As @cwilso notes in https://github.com/w3c/PWETF/issues/231#issuecomment-1422842218, "micro-aggressions" is the commonly accepted term. We can discuss and debate its propriety, but I think we'd do so at the risk of letting nuance and correctness triumph over readability and making the point in terms most people will understand without needing to look them up.

**Comment by hober** [comment]
I think it would be a mistake for the CEPC to deviate usage from the widely-accepted common term, as @cwilso & @LJWatson point out.

**Comment by dbooth-boston** [comment]
Okay, I think I've heard enough pushback on this suggestion that I'll withdraw it and close this issue.  Thanks all!
