### ISSUE TITLE
Clarify bullets on "patronizing language or behavior"

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/PWETF#232]
This issue separates out (and supersedes) suggestion 11 from https://github.com/w3c/PWETF/issues/228 , and subsumes https://github.com/w3c/PWETF/issues/225 .

BACKGROUND: Section 3.2 (Unnacceptable Behavior) currently has a bullet section that reads:

[[

- Patronizing language or behavior:

  - Be aware that, regardless of the speaker's intentions, some phrases or constructions lead people to expect a patronizing statement to follow, and avoid such phrases. For example, beginning an interjection with "Well, actually..." can set this expectation and be taken as a sign of disrespect.
  - Assuming without asking that particular people or groups need concepts defined or explained to them. It’s great to be sensitive to the fact that people may not be familiar with technical terms you use every day, but assuming that people are uninformed can come across as patronizing.
  - Assuming that particular groups of people are technically unskilled (e.g., “So easy your grandmother could do it”).

]]

SUGGESTION: Replace the above with the following bullets:

[[

- Use of trigger phrases that may distress or offend certain groups or individuals. Be aware that some terms, though neutral in their original meanings, now have offensive connotations within some groups. For example, "thug" now carries racial undertones to some. 

- Patronizing language or behavior, such as assuming that particular individuals are less competent or skilled based on their appearance, nationality, gender identity or any other characteristic that is irrelevant to the objective.  Note also that "Well, actually . . ." (as an interjection) is a trigger phrase to some, and may be taken as a patronizing sign of disrespect.

- Pedantic or repeated corrections that don’t contribute to the conversation.

]]

EXPLANATION:  1. It's important not to imply that speakers can avoid defining their jargon, as further explained  in https://github.com/w3c/PWETF/issues/225 . 2. It is helpful to point out that there are many terms or phrases that, though neutral or seemingly neutral to many, are offensive trigger phrases some, and should be avoided. We should not assume that the reader already knows all trigger terms (which is not possible).  For example, the original text assumes that the reader is aware that "Well, actually" is a trigger term, but this is far from universal knowledge, so it helps to explain it.  3. This clarifies that one should not make assumptions about certain groups or individuals based on characteristics that are _irrelevant to the work objective_.  4. This suggestion also attempts to address this comment (which was previously neglected?), though the wording has been changed: https://github.com/w3c/PWETF/pull/46#discussion_r273520758

**Comment by TzviyaSiegman** [comment]
@dbooth-boston please review and close if this is addressed by other issues

**Comment by dbooth-boston** [comment]
> @dbooth-boston please review and close if this is addressed by other issues

Sorry, I failed to notice this request earlier.

Yes, I think the issue has been addressed well enough for this iteration of the document.  Closing the issue.
