### ISSUE TITLE
Definition of "Microaggression"

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/PWETF#235]
This issue separates out (and supersedes) suggestion 15 from https://github.com/w3c/PWETF/issues/228 .

[The glossary](https://www.w3.org/Consortium/cepc/cepc-20200716/#glossary) currently defines microaggression as:

> Microaggression is a term used for brief and commonplace daily verbal, behavioral, or environmental indignities, whether intentional or unintentional, that communicate hostile, derogatory, or negative prejudicial slights and insults toward any group, particularly culturally marginalized group.

The problem is with the word "unintentional". The word "aggression" inherently involves intent, so it doesn't make logical sense to talk about "unintentional aggression".  (If I step on someone's foot in a crowded subway because I am jostled, it may injure the person, but it is not aggression.)  However, it can make sense to talk about "unconscious aggression". 

SUGGESTION 15: In the definition of microaggression, change "whether intentional or unintentional" to "whether conscious or unconscious" so the definition would read (with minor grammatical issues also corrected):

> Microaggression is a term used for a brief and commonplace daily verbal, behavioral, or environmental indignity, whether conscious or unconscious, that communicates a hostile, derogatory, or negative prejudicial slight or insult toward any group, particularly a culturally marginalized group.

I am probably more sensitive to logically consistent word usage than most people, so I realize I may be in a minority here, but it always bothers me when words are used in nonsensical ways. Many definitions of "microaggression" include "unintentional", but not all. I would prefer that we avoid that logical inconsistency.

Variation 15a: A second option would be to change the definition to "an indirect or subtle action or statement regarded as denigrating a minority or marginalized group", as adapted from the Collins dictionary definition:
https://www.collinsdictionary.com/us/dictionary/english/microaggression

Variation 15b: A third option would be to change the definition to "everyday subtle put-downs directed towards a marginalized group which may be verbal or non-verbal and are typically automatic", taken from this PubMed article on microaggressions:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6565651/

**Comment by TzviyaSiegman** [comment]
@dbooth-boston your proposals for changes are fine. I have no objections to them, but are there problems with our existing definition?

**Comment by dbooth-boston** [comment]
As described above in the description, it is purely an issue of English usage, and not one that is important enough to waste any sleep over.  I was mainly suggesting changing "whether intentional or unintentional" to "whether conscious or unconscious".  But if most others prefer not to make that change, then I'm fine with keeping that phrase as is.

However, I would still suggest at least correcting the multiple grammatical errors in the existing definition, so it would read as follows.

Variation 15c:
>> Microaggression is a term used for a brief and commonplace daily verbal, behavioral, or environmental indignity, whether intentional or unintentional, that communicates a hostile, derogatory, or negative prejudicial slight or insult toward any group, particularly a culturally marginalized group.

**Comment by cwilso** [comment]
This is fine - and I noticed the same plurality error at the end of the paragraph - but I would point out that in the original, "Microagression" was being defined as a pattern of actions - a collection of hostile behaviors - not just a single instance of the same; I don't think that was a grammatical error, just a choice.  I'm not tied to either way of expressing this.

**Comment by nigelmegitt** [comment]
>commonplace daily

Isn't this tautological? Also, if you define it as "daily" then someone some time is going to say "but I only did it on Mondays, Wednesdays and Fridays" so it wasn't a microaggression. Suggest changing "commonplace daily" to "frequent".

**Comment by dbooth-boston** [comment]
> in the original, "Microaggression" was being defined as a pattern of actions

That's a good point.  On further reflection, I think it would be better to describe it as a pattern of actions, since the pattern is what really causes the major harm.

**Comment by nigelmegitt** [comment]
> So I suggest "common" instead of "commonplace daily" or "frequent".

I'm neutral about this: to my mind "common" and "frequent" are synonyms in this context.

**Comment by dbooth-boston** [comment]
This issue was discussed on [April 25](https://www.w3.org/2023/04/25-pwe-minutes.html).  There was some confusion in that discussion over the word "pattern" in the wording proposed in https://github.com/w3c/PWETF/pull/241 , and whether a pattern is needed for an action to qualify as a microaggression.  Two points to note:

1. The proposed wording in https://github.com/w3c/PWETF/pull/241 uses the word "pattern" because it is describing the concept of microaggression _in_ _general._  It is _not_ attempting to define a single _instance_ of microaggression.  Clearly no pattern is needed for an action to qualify as a single _instance_ of microaggression.  But the whole point of microaggression as a concept is that, although a single instance may seem to have only a small impact, the _cumulative_ effect of microaggression has a major impact.  That's why the term was coined.

2. The existing wording already implicitly describes the concept of microaggression as a pattern, though it does not use the word "pattern".  Note that it uses plural language and it describes microaggression as "commonplace" and "daily".  That is describing a pattern, though again a single _instance_ of microaggression does not need to be a pattern in itself.

If the group instead prefers to define "microaggression" as a single _instance,_ rather than as a general concept, then we could try to craft such a definition, but I personally found it easier and more informative to define the concept as a whole, precisely because the idea that _a pattern of small harms can have much larger cumulative effect_ is central to the concept of microaggression.

**Comment by TzviyaSiegman** [comment]
I recommend leaving the wording as is. Looking at many definitions of microaggressions online, the word "pattern" is not mentioned. See https://www.merriam-webster.com/dictionary/microaggression, https://en.wikipedia.org/wiki/Microaggression, https://www.med.unc.edu/healthsciences/about-us/diversity/jeditoolkit/microaggressions-microaffirmations/ for a sample. I don't think we should break from the standard definition.

**Comment by dbooth-boston** [comment]
I don't mind leaving out the word "pattern", but it would nice to at least improve the wording.

A glossary definition that begins with "Microaggression is a term used for" is just plain bad writing.  It is unnecessarily wordy.  OBVIOUSLY "microaggression" is a term.  There is no need for the definition to say that it "is a term".  

There are several ways the writing could be improved without changing the important meaning.  If the group wants to (continue to) define microaggression as a _general concept_ -- i.e., multiple instances -- then here are some ways the beginning of the definition could be shortened:

- "Microaggression refers to brief and . . . "
- "Brief and . . ."

If the group instead wants to define microaggression as an _instance_ -- i.e., an individual event -- then the wording throughout the definition would have to be changed from plural to singular, something like this:

> A brief and commonplace daily verbal, behavioral, or environmental indignity, whether intentional or unintentional, that communicates a hostile, derogatory, or negative prejudicial slight and insult toward any group, particularly a culturally marginalized group.

**Comment by dbooth-boston** [comment]
I just noticed that the wikipedia definition has improved since it was originally copied into this document.  It is better written now.  I suggest we start with [the latest wikipedia version](https://en.wikipedia.org/wiki/Microaggression).

If the group does not want to start with the latest wikipedia version, then I also suggest these editorial changes to the definition:

1. Change "culturally marginalized group" to "a culturally marginalized group".  (Missing article)
2. Delete the word "daily".  Microaggression doesn't have to be daily to be microaggression.
3. Change "particularly" to "especially".  "Especially" is a better word choice here -- and is what dictionaries normally use in this context.   Some senses of "particularly" are restrictive, but it wouldn't make sense to restrict "any group" to "culturally marginalized" groups.

**Comment by wareid** [comment]
Agreed on rewording: Microaggression refers to commonplace verbal, behavioral, or environmental indignities, whether intentional or unintentional, that communicate hostile, derogatory, or negative prejudicial slights and insults toward any group, especially culturally marginalized groups.
