### ISSUE TITLE
The Goal of the CEPC sets a rather low bar

### ISSUE THREAD

**Issue by dwsinger** [w3c/PWETF#250]
The introduction says 

> "The goal of this code of conduct is to ensure that W3C is an environment where everyone can participate without fear of [harassment](https://www.w3.org/Consortium/cepc/#dfn-harass)."
> 
> Harassment
> Any conduct, verbal or physical, that has the intent or effect of interfering with an individual, or that creates an intimidating, hostile, or offensive environment.

I am concerned that this expresses the goal in the negative ("avoid harassment") and sets a very low bar. I would prefer that we set the goal that we (positively) treat people with respect, and treat everyone equitably. I don't think a response from a culprit "well, I didn't actually harass anyone" should be even close to being a defense.

Something like:

"The goal of this code of conduct is to ensure that W3C is an environment where everyone who participates is treated equitably and with respect, including being to participate without fear of harassment."

**Comment by TzviyaSiegman** [comment]
I believe https://github.com/w3c/PWETF/pull/236 addresses this

**Comment by dwsinger** [comment]
@TzviyaSiegman I don't think it does, but it could more easily. The new document there has

The goals of this code are to:

-  Ensure an environment where people can participate without fear of harassment.
-  Ensure transparency in community and group management.
-  Contribute to the identity of the organization.

And again the first bullet starts with that low bar. I'd like to see an additional bullet, before the others:

- ensure that everyone who participates is treated equitably and with respect

**Comment by HEXYEBO0** [comment]
- [ ]

**Comment by nigelmegitt** [comment]
I'm not convinced that the goal of the CEPC is to ensure transparency in community and group management. That feels like a good goal that should be written down somewhere else.
