### ISSUE TITLE
Incorporate Procedures into CEPC?

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/PWETF#29]
Is there a reason that [Procedures](https://www.w3.org/Consortium/pwe/#Procedures) is a separate document from CEPC? Would it be okay to make Procedures a part of CEPC?
@jeffjaffe @wseltzer @swickr

**Comment by jeffjaffe** [comment]
@TzviyaSiegman I think the information architecture is that we have the PWE home page https://www.w3.org/Consortium/pwe/ and it points to its two distinct key resources the Code and the Procedures.

**Comment by TzviyaSiegman** [comment]
Thanks, @jeffjaffe. I think it's a little confusing that Procedures is part of the PWE home page. I honestly didn't realize that PWE had a home page until you pointed it out. I am proposing consolidating all info into one document, the CEPC. Feedback welcome.

**Comment by swickr** [comment]
The [published CEPC](https://www.w3.org/Consortium/cepc/) states

> This code (CEPC), complemented by a set of [Procedures](http://www.w3.org/Consortium/pwe/#Procedures) ...

with the idea that the latter might be revised on a different cycle and possibly with different review than the former.

I would not be comfortable combining them into a single document.  The Procedures could, however, be its own document distinct from a "home page".

**Comment by TzviyaSiegman** [comment]
Thanks for the feedback. I've added a new doc to the repo.
