### ISSUE TITLE
Add Process to CEPC

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/PWETF#3]
Current CEPC does not identify clear Process for chairs or others to follow when there is a violation. 

Clear process will be helpful for those handling violations as well as those who have violated the CEPC in recognizing potential consequences. Many of the [sample CoCs listed in References and Resources](https://w3c.github.io/PWETF/ReferencesAndResources#codes-of-conduct) include Process.

See also [PWETF-only email](https://lists.w3.org/Archives/Member/member-pwetf/2017OctDec/0019.html).

**Comment by tripu** [comment]
[Description edited slightly just to fix the link to &ldquo;References and Resources&rdquo; &mdash; tripu]

**Comment by nigelmegitt** [comment]
I just raised #34 and see that it is a subset of the process which this issue calls for.

**Comment by TzviyaSiegman** [comment]
This has been addressed by the [Reporting](https://w3c.github.io/PWETF/#Reporting) section and will be further addressed once we update the Procedures document
