### ISSUE TITLE
Clarify update cycle

### ISSUE THREAD

**Issue by chaals** [w3c/PWETF#314]
The current text seems to mix the idea that issues will be considered and accepted in the three month review period that runs from March to July, as well as that you can file concerns at any time.

It seems the intention is that PWE will spend 3 months from March to June considering issues, and expects to have resolved them all (by July 1, or 31, or...?) and present a new proposal.

It would help if the review period were specified as when the PWE will actively work on issues raised until that time, and examine the document and current practice to determine if there are other issues that have not been noted. It would also help if dates were given, not just a month.

Finally, "issues and concerns" actually seems quite vague. it would help to know what the group wants, whether that is tightly scoped like "problems that the CoC apparently doesn't cover", or as broad as "any questions about the CoC and how it works" (or something else).

**Comment by TzviyaSiegman** [comment]
is fixed by #328
