### ISSUE TITLE
Use of 'Never' statements in CEPC

### ISSUE THREAD

**Issue by RachelComerford** [w3c/PWETF#32]
(From https://github.com/w3c/PWETF/pull/28)

@vlevantovsky:
in my initial comment I specifically stated exactly what I think. To my ear, "violations of CEPC" has a very different meaning compared to "concerns about CEPC".
I have long-standing concerns about CEPC, specifically because it is written using a language that defies the stated goals of "treating each other with respect" and "communicating constructively". Saying to anyone "don't be a bully!" is hardly respectful, saying "Never be a bully!" is even more disrespectful since it implies that someone has been a bully all along. At our previous call, when you asked for specific editorial suggestions, I suggested to get rid of, and/or rephrase any statement that starts with "Never ...", which has since been ignored.

**Comment by RachelComerford** [comment]
@RachelComerford:
If I'm reading this accurately (please let me know if I'm misinterpreting) you are expressing two, not necessarily connected concerns here.

The move from "violations" to "concerns"
- I see what you're saying, this is definitely less concrete. While a clear violation of the rules is certainly the easiest to address, the idea here is to leave space for people to come forward to speak even if they are not sure of a hard and fast violation. Having talked to you, I know you feel very comfortable having constructive conversations about difficult topics and often have quite a bit to say about them. You know I can do the same! But not everyone has that comfort level and it's certainly not a requirement for participation so we need to give everyone a path and tools for a constructive conversation. In this case, it's a concern that something is wrong and likely, the seeking of help from an ombuddy for advice or resolution.

There are statements in the document that begin with the phrase never which read to you as assuming the audience has already done something wrong.
- Getting rid of these entirely would be a mistake; they likely address key ideas. To make this more constructive, could you identify the phrases you find problematic and suggest some rephrasing? As I went through it as a potential audience member, there was nothing I felt particularly targeted by, so it would be helpful to have detailed information and suggested remediation from someone who did have those concerns.

**Comment by RachelComerford** [comment]
@vlevantovsky:
My biggest concern about CEPC, as written, is what I stated earlier - it's counter-productive and the language we use is neither "respectful" nor "constructive communication". The fact that both I and Ada Rose Cannon took time and effort to completely rewrite it, and that both of us, independently from one another, chose to follow a different path where we wanted to clearly state what behaviors are not tolerated and what behaviors are encouraged (instead of telling people what NOT to do) is quite telling. The essential part of my proposal to get rid of statements starting with "Never" is to replace them with a clear and unambiguous statements defining the behaviors that will not [ever] be tolerated (we discussed it at lengths during the call). Once we have this in place ...

**Comment by RachelComerford** [comment]
@RachelComerford:
I think it's important that we not speak for others here, so I will set aside responding for @AdaRoseCannon. If she has time, it would be great to hear her thoughts and recommendations for rewrites.
About removing the "never" statements - I don't really see anyone here articulating that this would be an issue. In order to remove them or revise them, someone first needs to call them out individually and suggest rewrites. Now that you've identified something that you find problematic for you - are you willing to contribute to constructing the solution?

**Comment by RachelComerford** [comment]
@vlevantovsky:
I did propose a solution, something that was reviewed and contributed to by many members of the Positive Work Environment Task Force (including both co-chairs who contributed their comments and edits). And I do not speak for @AdaRoseCannon here, the version of the Code of Conduct she wrote for Immersive Web group is linked in the header of this very issue we are discussing.

**Comment by vlevantovsky** [comment]
I think we have successfully accomplished the stated goal - there are no more "never" statements left in the current version of the text, and most of the good stuff has been moved from PWETF draft to the current text. Consider it a success story!
