### ISSUE TITLE
PWE page still refers to Director

### ISSUE THREAD

**Issue by gsnedders** [w3c/PWETF#384]
https://www.w3.org/about/positive-work-environment/#Procedures says:

> Note: In exceptional circumstances, the W3C Director may ban an individual from participating in our activities, e.g. on a mailing list or in a group (refer to [section 3.1.1.3 of the W3C Process Document](https://www.w3.org/policies/process/policies.html#member-rep)).

This is both a broken link, and refers to the W3C Director.

https://www.w3.org/policies/process/20231103/#discipline is presumably where this should reference, which says:

> The [CEO](https://www.w3.org/policies/process/20231103/#ceo) may take disciplinary action, including suspending or removing for cause a participant in any group (including the [AB](https://www.w3.org/policies/process/20231103/#advisory-board) and [TAG](https://www.w3.org/policies/process/20231103/#technical-architecture-group)) if serious and/or repeated violations, such as failure to meet the requirements on individual behavior of (a) this process and in particular the CEPC, or (b) the membership agreement, or (c) applicable laws, occur. Refer to the [Guidelines to suspend or remove participants from groups](https://www.w3.org/Guide/process/banning.html).

**Comment by koalie** [comment]
Fixed in place, thanks!

**Comment by koalie** [comment]
I also updated the Guidebook page "[Guidelines to suspend or remove participants from groups](https://www.w3.org/Guide/process/suspension.html)"

**Comment by koalie** [comment]
I also opened an [issue](https://github.com/w3c/process/issues/922) against the W3C Process to no longer refer to "CEPC" and "Code of Ethics and Professional Conduct", but to "Code of Conduct" or "Code"
