### ISSUE TITLE
Privacy and confidentiality

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/PWETF#42]
Add section about privacy and confidentiality. 
* Consider sentence removed from PR#36 "Respect people’s right to privacy and confidentiality. "
* Consider language proposed by PWETF 

> Confidentiality and privacy. Sometimes, matters we discuss may fall under various confidentiality agreements and strict adherence to these agreements is expected. In addition, certain pieces of information disclosed in a group setting may be private in nature, or we may inadvertently learn confidential information accidentally disclosed by other participants. Please exercise good judgment, and make reasonable efforts to protect privacy and confidentiality of all participa

**Comment by vlevantovsky** [comment]
I support the change proposed by @TzviyaSiegman

**Comment by TzviyaSiegman** [comment]
This is the language in current draft.
