### ISSUE TITLE
Consider editorial restructuring of the Expected Behavior section

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/PWETF#43]
Topics like Privacy, Confidentiality, Cultural differences, and Respect deserve their own paragraphs. Also, there are currently few different paragraphs that speak on the subject of Respect in one way or another, could be consolidated for clarity.

**Comment by TzviyaSiegman** [comment]
@vlevantovsky has this been addressed sufficiently in the current draft. Please close this issue if it is.

**Comment by vlevantovsky** [comment]
Some recent changes did address some parts, but I think there is more we can do to clean it up.

- The first paragraph (treat each other with respect ...) is a duplication of what has already been stated in the opening introduction statement of CEPC, and is probably redundant, considering that the next two bullet points speak on the same topics in more details;
- The word "respect" in the first paragraph also has a broken link that used to point to its corresponding "Glossary" entry, which has since been removed. If we simply delete the first bullet point we will solve both issues;
- Purely editorial nit: some paragraphs of "Expected behavior" section have bold type subheadings, and some don't - considering that this is a bulleted list of items, and that the prior section ("Unacceptable Behaviors") is also a bulleted list that doesn't have any entries using bold type, I'd suggest to remove bold type and make both parts of CEPC uniform in appearance.
