### ISSUE TITLE
add section to "unacceptable" about reverse -isms

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/PWETF#44]
Proposed text from PR #37 

> The Geek Feminism community prioritizes marginalized people’s safety over privileged people’s comfort. The Geek Feminism Anti-Abuse Team will not act on complaints regarding:
> 
> * ‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’ (because these things don’t exist)
> * Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you.”
> * Refusal to explain or debate social justice concepts
> * Communicating in a ‘tone’ you don’t find congenial
> * Criticizing racist, sexist, cissexist, or otherwise oppressive behavior or assumptions

**Comment by vlevantovsky** [comment]
I have mixed feelings about adding these statements to the CoC. 
First [like I mentioned during the call], I'd like to keep CoC neutral - it is not about men's rights activism or women's rights activism, or any other community activism - it's about gender equality. A more active  stance taken by the Geek Feminism community may be perfectly acceptable for that particular community, but W3C is a worldwide organization and we definitely want to keep the language of the W3C CoC gender-neutral. 
Also, making explicit claims that certain things do not exist or will not be acted upon creates a dangerous (IMO) precedent that opens other things to be considered subjects for interpretation - I'd rather avoid that. E.g., how can we uphold tone-base bullying defined by one part of CoC (and protect people from being subjected to it), when there is another part of the language that says we will not act on the complaints related to communicating in a 'tone' one doesn't find congenial?
(Off-topic example: Sometimes saying less is actually more, e.g. German "distracted driving" law would be a good example - they don't specify whether drinking water, or coffee, or talking on the phone while driving is prohibited; instead, any drivers' action that is causing distracted driving is against the law.)

**Comment by torgo** [comment]
Disagree, @vlevantovsky. I think the whole reason we are here, doing what we are doing, is that the neutral approach has not worked. Claims of reverse-sexism can often be used by bad actors to make environments less inclusive and less friendly.  This is one reason why we need a more active management of these issues that "prioritizes marginalized people’s safety over privileged people’s comfort." This is the current best practice in the tech community - and we need to incorporate this into our thinking if we are really serious about being inclusive.

**Comment by vlevantovsky** [comment]
@torgo, I _am_ serious about being inclusive, and this is exactly why I find the language that speaks about prioritizing "marginalized people’s safety over privileged people’s comfort" divisive and inflammatory, something that is contrary to the very principles of W3C. 

We have a multifaceted, multicultural community of participants from all over the world - how do we decide who is marginalized and who is privileged? Would a foreigner speaking English as a second language be marginalized, and the native English speaker privileged? Or, would you consider a happy, healthy representative of LGBTQ community marginalized, and the straight person with disability privileged? Or, the other way around? 

What do we really say by telling people we prioritize "marginalized people’s _safety_ over privileged people’s comfort" - has anyone's safety ever been threatened in the W3C, and by who?

In my opinion, this particular statement of intent brings no value to CEPC "Unacceptable Behavior" section, and creates more problems than it solves. The purpose of the "Unacceptable Behavior" is to provide clear and concise definition of the types of behaviors that will not be tolerated (more about it later), and not impose any prejudicial judgement as to who we should expect to be a potential violator of our Code, and why.

**Comment by boazsender** [comment]
@TzviyaSiegman I support those additions. We use similar language in the [Bocoup Code of Conduct](https://bocoup.com/code-of-conduct) as well. Thanks so much for proposing that change and for leading this work!

@vlevantovsky I totally hear you, but I have to agree with @torgo here. We have a real history of systematically excluding folks from participating in web standards, and then getting upset or uncomfortable when that behavior is called out, further alienating those folks from participating. So I think it is important to be explicit in our code of conduct that that is not acceptable behavior.

**Comment by torgo** [comment]
@vlevantovsky again, I think you really need to spend more time listening to what people in marginalised communities are saying. I don't view your input on this thread as either helpful or productive. Quite the opposite: the approach you are taking here is having the effect of driving away the exact people we need to be engaging right now.

**Comment by dauwhe** [comment]
I fully support the proposed text. I've seen many examples online of people using such tactics in bad faith. 

When thinking about a code of conduct, I try to imagine the response of someone who has had bad experiences in the past. Does the CoC appear to be serious about addressing potential harm? Or is it just platitudes written to make (some) people feel better? We are trying to send a message that we will actively work to make our community better, more welcoming, safer. I think statements like the one at the top of the thread will help.

**Comment by TzviyaSiegman** [comment]
By definition, a code of conduct is not neutral. In fact, it is intended to make people think about their actions. I am not questioning anyone's intentions or seriousness about making people feel included. However, a code of conduct is here to guide _actions_ not intent. No individual is being asked to decide on the definition of marginalized people. The proposal on the table is to add language to the CEPC that will deem unacceptable those who might try to use the CEPC to defend the very behaviors we are trying to prevent. 

Let us not assume that we understand what it is to be marginalized without having been there ourselves even if we fall into traditional categories of marginalized people. This is asking the reader to appeal to empathy, putting oneself in another's shoes. I feel very strongly that it is a good idea to include a section indicating that the CEPC does not protect those who criticize racists in the same way that it protects those who are the subject of racism. 

If the concern is that someone who is critical of minorities or marginalized communities feels uncomfortable about their behavior, then I think we have accomplished our goal of making people think about their actions. If there are other concerns please provide evidence that such statements are poorly received.
