### ISSUE TITLE
Use Mediator instead of Ombud

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/PWETF#53]
I've noticed the use of the term Ombud has never quite settled well and has been discussed from time to time. After discussing this with someone not involved in W3C work I realised that Ombud may give the wrong impression.

There are several definitions of an ombudsman in use ("ombud" isn't actually in the dictionary yet) – some of them include getting to resolution, but mostly they are about investigating and making a final decision. 

The CEPC currently goes from potential violation directly to referral to an Ombud if no speedy resolution occurs; that is highly suggestive of a process where the Ombud investigates and _makes a decision_ about who is in the right or wrong, yet the described role of the Ombud quite rightly describes a process of _getting to a resolution_. 

"Ombud" therefore gives the impression of an _investigator_ and an _arbitrator_ rather than a _mediator_ who, as the role describes, helps the parties involved work towards a resolution.

I think we should emphasise the mediation part of the role in favour of the decision making part.

A closer term for someone whose main role is to get to a resolution of a conflict between two or more parties is _Mediator_, so I propose that we:

* use Mediator in place of Ombud globally

**Comment by swickr** [comment]
From the [IOA](https://ioa.memberclicks.net/what-is-an-organizational-ombuds)
> At the most fundamental level, an ombudsman is one who assists individuals and groups in the resolution of conflicts or concerns.

For me, "assists" is key

**Comment by nigelmegitt** [comment]
@swickr if the IOA definition were commonly understood, that would be fine - my point is that it isn't what many people initially think of when they think of an ombudsman; the IOA isn't generally well known amongst the public at all, I'd argue. 

The issue here is the impression it gives, of "investigate and decide" vs "work collaboratively towards a resolution". I think we should be setting a tone of "we work collaboratively to resolve issues" primarily and "if we really are stuck, we have a route to force a resolution" secondarily.

___
Further detail on the generally understood meaning.

Oxford English Dictionary has:
> 1. a. Politics. Originally: an official appointed by the Swedish parliament to investigate complaints against maladministration by central government and the civil service. Later: an official with a similar role in another country; spec. (in Britain) the Parliamentary Commissioner for Administration.
> 1. b. A person appointed to investigate complaints against maladministration by a particular category of organization or in a particular area of public life, such as local authorities, hospitals, or pensions.
> 2. In extended use: a person who handles complaints, a mediator; a spokesperson for the rights of a particular individual or group.

[Wikipedia](https://en.wikipedia.org/wiki/Ombudsman):
>... an official who is charged with representing the interests of the public by investigating and addressing complaints of maladministration or a violation of rights. ...

Also [Merriam-Webster](https://www.merriam-webster.com/dictionary/ombudsman), [dictionary.com](https://www.dictionary.com/browse/ombudsman),  [Collins](https://www.collinsdictionary.com/dictionary/english/ombudsman) - in all these the definition is primarily about investigation and, if at all, secondarily about getting to a resolution.

**Comment by brewerj** [comment]
Further on this topic:  My understanding is that we should, however, improve our procedures, and making those clear. Nigel, hoping this helps your concern from a different direction?

**Comment by swickr** [comment]
Resolved in the 31-October CG call to keep the name "Ombuds"
