### ISSUE TITLE
Improve details of reporting sections.

### ISSUE THREAD

**Issue by AdaRoseCannon** [w3c/PWETF#56]
It is very important that the section on reporting has clear procedures with explicit contact details for people to contact.

The person making the report may be distressed and parsing an external document to find who they should report to is too much to ask. I think that the essential information from the [procedures section](https://www.w3.org/Consortium/pwe/#Procedures) of the PWE page be included here. I think the structure should look like so, in first contact priority.

1. #51 will add rapid-response information so that is 👍 
1. Related to #41 I think ideally chairs should be the first people to contact, to try to solve issues within the group. If the issue cannot be resolved to the hurt parties satisfaction the chair should help raise it with an ombud to get it resolved.
1. In addition I think large groups may also want to nominate people who things can be reported to. So that they may either report to the chairs or bypass the chairs entirely if the chair is the issue.
1. In the case of the hurt party not feeling that the Chair will support them or the chair being an issue themselves they should feel safe raising it with ombuds themselves. If the hurt party is the chair and need to raise a grievance with the ombuds that is something you should also feel free to do. If you need assistance raising the issue please contact [contact]
1. [Table of Ombuds with contact details]

The reporting section should probably also include additional information about TPAC as well as reporting in live events should be able to be accomplished by speaking to someone who is identifiable and providing onsite contact information.

This section may want to still link out to the [existing reporting document](https://www.w3.org/Consortium/pwe/#Procedures) in this section but I am concerned it may make things unclear to whoever is reading it, so perhaps it should be an addendum.

Edit: Add person for chairs to report to.

**Comment by nigelmegitt** [comment]
In general I like the idea of having the escalation process in the CEPC

> parsing an external document to find who they should report to is too much to ask

I don't see the distinction: clicking a link to find a "here's what to do" list in a _separate_ document is a hair's breadth away from clicking a table of contents link to find that same text in the same document. You click a thing, you get the answer. 

> bypass the chairs entirely if the chair is the issue

+1, also there needs to be someone for the _Chair_ to go to if they are directly affected.

**Comment by AdaRoseCannon** [comment]
> I don't see the distinction: clicking a link to find a "here's what to do" list in a separate document is a hair's breadth away from clicking a table of contents link to find that same text in the same document. You click a thing, you get the answer.

People who are looking for this are likely scanning the document rather than reading. A link can go easily missed, a table of names and emails you should report to is more visible to someone scrolling.

 If we need to include more detail we can link to the external document in addition.

> +1, also there needs to be someone for the Chair to go to if they are directly affected.

Good point I will edit my initial proposal.

**Comment by TzviyaSiegman** [comment]
I agree. We discussed briefly in https://github.com/w3c/PWETF/issues/3. @jeffjaffe what do you think?

cc @jorydotcom re ombuds documentation

**Comment by jeffjaffe** [comment]
First, I definitely agree that we should massively improve the guidance on how to deal with situations as they arise.

For Ada's item #2, I think there are a few different subcases:

- I also think that Chairs have a responsibility to recognize issues even if not formally brought to them.  I think we need a module on how that works.

- I don't agree that Chairs should always be the first people to be contacted.  For the person who feels offense, they need to determine who to contact first.  That could be a chair, it could be an ombuds.

I'm still thinking about Ada's item #3.  I see the need, but it is also a little strange to have per-group ombuds - as opposed to utilizing the W3C - ombuds (who presumably have better training and more experience).

More generally, we should improve the "best practices" training for the ombuds, so there is a uniform approach of how they do their task.

**Comment by AdaRoseCannon** [comment]
Thanks for the feedback @jeffjaffe. Regarding your second point I believe we are on the same page. I think both Chair's and Ombuds should be considered for the first point of contact depending on the situation. I should make that clear when writing the proposal.

I agree with your first point too, but do you think that it should also apply to anyone within the W3C, so a *'If you see something which you feel violates the CEPC...'*

**Comment by jeffjaffe** [comment]
@AdaRoseCannon 
I have been party to several situations in which a person feels that they were not treated professionally within W3C, but does not want to formally lodge a complaint.  There could be numerous reasons that this happens.  Accordingly, it might be awkward for "anyone" to be empowered to raise an issue on behalf of "anyone" else.

However, for Chairs and Team Contacts, since they have authority to ensure that their groups run professionally, they should be empowered to recognize problems on their own and address them.

This distinction that I am making (which is only my opinion - others may disagree) is part of why I think we need to beef up guidance on dealing with problems - today it is barely written down who may do what.

**Comment by brewerj** [comment]
+1 to having alternatives to reporting issues to Chairs, as it is possible that an issue could be about a Chair. 

And having well-vetted Ombuds, and known procedures that the Ombuds can use, should increase people's confidence in being able to report issues to Ombuds.

**Comment by AdaRoseCannon** [comment]
From the call: Keep the reporting path free so the person reporting can decide who to approach, okay to make a PR.

**Comment by AdaRoseCannon** [comment]
Action: Move line regarding 'we will take all complaints seriously' from the #57 to the reporting section.

**Comment by AdaRoseCannon** [comment]
I have opened #63 I have tried to address everyone's feedback if you feel something is missing please comment in that PR.

**Comment by AdaRoseCannon** [comment]
PRs merged
