### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/PWETF#62]
Following the discussion during our [WebEx call on July 25th](https://www.w3.org/2019/07/25-PWE-minutes.html), I'd like to raise the issue about Glossary with a different (positive) spin. My dislike of the current content of "Glossary" has already been documented in issue #40 , but I do agree that the Glossary can be a useful tool if the content of it is useful, and the way it is delivered follows the same principles we outlined in the new CEPC.
With this in mind, I suggest that we should apply the following principles when determining what should be part of the "Glossary" and why:
1) Any explanation of a concept or a word that can be easily found in  English dictionary doesn't need to be duplicated in the Glossary - it does come across as patronizing when we are assuming that people need basic concepts (such as e.g. "acknowledgement" and "respect") explained to them. Most people in English speaking audience wouldn't benefit from it, and anyone who might need an explanation can easily find it in a dictionary.
2) Since W3C is transitioning to legal entity, I suspect that certain concepts that are directly relevant to employer/employee relationships would be outlined elsewhere. The CEPC is a community document, therefore, its content, and terms and definitions used as part of it (including Glossary) should reflect this specific scope.

As far as actual content of Glossary section is concerned, I propose that each PWE CG member (and will do it myself) should review the latest CEPC draft and would use comments on this issue for any suggestions of the terms used by CEPC that they want to see covered by the Glossary.

**Comment by AdaRoseCannon** [comment]
There are some terms, such as "outing", which although they are in the dictionary they were unfamiliar to some people working on this document.

In addition, terms like "outing" have domain specific meanings which may be worth specifying. "outing, as to go somewhere on a trip" vs "outing, revealing someone's sexuality against their will"

I think if something is in the dictionary it shouldn't necessarily preclude it, and should still be considered for adding to the glossary if someone is unfamiliar with it.

**Comment by vlevantovsky** [comment]
I agree that any term used in CEPC with a meaning that is different from its typical dictionary definition ought to be defined in Glossary to avoid any possible confusion. (In this regard, the term "outing", as Ada mentioned, clearly falls in that category and needs to be defined).
Also, the following terms (listed in no particular order other than as they appear in the CEPC text) need to be defined as I couldn't find any official dictionary definitions for them:
neurotype, microagression, reverse racism, reverse sexism, cisphobia, cissexist.

**Comment by judy-zhuhr** [comment]
While looking at the new version of CEPC, I picked out the following items as a candidate glossary list with benchmarks such as:
1. Basic terms that have to be clearly explained for people to fully and correctly understand this document
2. Terms that might have different meanings in different cultures 
3. Terms that people whose native language is not English might seldom use or meet 
4. Terms that has a specific meaning in W3C context   

==================candidate glossary list ============

1. abusive behavior
2. acceptable behavior
3. accepted behavior
4. bullying
5. cisphobia
6. cissexist
7. communicate constructively
8. consensus 
9. dead-naming
10. demeaning behavior
11. disability
12. discrimination
13. Diversity
14. enforcers of this Code
15. ethnicity
16. gender identity and expression
17. harrassment
18. inclusive
19. insulting behavior
20. intimidation
21. intimidation
22. marginalised communities
23. mental illness
24. Misgendering
25. neurotype
26. official standing
27. Ombudsperson
28. participants
29. Patronizing language or behavior 
30. personal behavior
31. physical appearance
32. professionalism
33. racist
34. reverse racism
35. reverse sexism
36. Reverse’ -isms
37. sexist
38. sexual orientation
39. socio-economic status
40. transparency

**Comment by lianqi** [comment]
While looking at the new version of CEPC, I picked out the following items as a candidate glossary list with benchmarks such as:
1.	Basic terms that have to be clearly explained for people to fully and correctly understand this document
2.	Terms that might have different meanings in different cultures
3.	Terms that people whose native language is not English might seldom use or meet
4.	Terms that has a specific meaning in W3C context
==================candidate glossary list ============
1.	abusive behavior
2.	acceptable behavior
3.	accepted behavior
4.	bullying
5.	cisphobia
6.	cissexist
7.	communicate constructively
8.	consensus
9.	dead-naming
10.	demeaning behavior
11.	disability
12.	discrimination
13.	Diversity
14.	enforcers of this Code
15.	ethnicity
16.	gender identity and expression
17.	harrassment
18.	inclusive
19.	insulting behavior
20.	intimidation
21.	intimidation
22.	marginalised communities
23.	mental illness
24.	Misgendering
25.	neurotype
26.	official standing
27.	Ombudsperson
28.	participants
29.	Patronizing language or behavior
30.	personal behavior
31.	physical appearance
32.	professionalism
33.	racist
34.	reverse racism
35.	reverse sexism
36.	Reverse’ -isms
37.	sexist
38.	sexual orientation
39.	socio-economic status
40.	transparency

**Comment by AdaRoseCannon** [comment]
"Consensus" is not mentioned in the document shall I still include it as it pertains to W3C process?

It may be an auto-corrected typo for "consent"?

**Comment by AdaRoseCannon** [comment]
"Transparency" is in the document to refer to being clear in our moderation practices. 

I just want to confirm this isn't an auto-correct of "transphobia"

**Comment by RachelComerford** [comment]
I'm in favor of including consensus in the context of the W3C process. The problem with excluding items that appear in the dictionary is that we lose the contextual relevance.

**Comment by vlevantovsky** [comment]
Alternatively, the problem with _including_ items not used in the text of CEPC is that we also lose relevance. Glossary is there to explain the terms we do use, not a substitute for a dictionary that is readily available elsewhere

**Comment by AdaRoseCannon** [comment]
I am personally for not defining "consensus" since it is not in the document. I think in this situation it is an auto-correct from "consent".

**Comment by vlevantovsky** [comment]
+1 to what Ada said. 
I think that we should simply follow a set of simple rules when determining the content of the Glossary section:

- if a particular term is not used in CEPC, it _should not_ be included in the Glossary;
- if a particular term used in CEPC has a common definition readily available from an English dictionary, it _should not_ be included in the Glossary;
- if a definition of a particular term used in CEPC  differs from its common dictionary definition, it _should_ be included in the Glossary;
- if a particular term is not found in a commonly used dictionary, it _should_ be included in the Glossary.

**Comment by RachelComerford** [comment]
Ah, @AdaRoseCannon apologies - I misread what you wrote - I thought you said it was in the document. In that case I agree with you and would not include Consensus.

**Comment by swickr** [comment]
[W3C Glossary and Dictionary](https://www.w3.org/2003/glossary/) exists and the work on Code of Conduct should avoid duplicating it.  There may be terms that are not unique to the CoC that we feel should be in the "big" glossary.  We can make sure that the terms in the CoC glossary get pulled into the big glossary as well.

**Comment by AdaRoseCannon** [comment]
Unfortunately neither "Transparency" or "Consensus" are in those glossary. Would we be able to put them there instead?

Also I was surprised the term "bikeshed" wasn't there either.

**Comment by swickr** [comment]
Resolved in the [31-October CG call](https://www.w3.org/2019/10/31-pwe-minutes.html#i62) to drop any glossary entries that do not have text by a deadline that Rachel and Jory will determine.

**Comment by TzviyaSiegman** [comment]
If CEPC is translated into multiple languages is it necessary to include all of these terms in the glossary? My feeling is that terms that are slang or require context should be included, but terms such as "constructive communication" might not need to be in the glossary.

**Comment by TzviyaSiegman** [comment]
Will be solved by #66
