### ISSUE TITLE
PWE CG Priorities

### ISSUE THREAD

**Issue by judy-zhuhr** [w3c/PWETF#64]
On the [2019-07-25 PWE CG group call](https://www.w3.org/2019/07/25-PWE-minutes.html ), CG discussed priorities, 3 items have been identified as following. 
1. CEPC draft, short term plan; 
2. Glossary, short term plan, listed separately from the CEPC draft because there now is an old version that hasn't gotten much work; Angel will provide a glossary list as a starting point. 
3. Ombuds training, long term plan;
 Need to confirm these priorities and make plans accordingly.

**Comment by TzviyaSiegman** [comment]
This issue has been absorbed into the [PWE Roadmap](https://github.com/w3c/PWETF/wiki/PWE-Roadmap)
