### ISSUE TITLE
Be careful when mentioning sexual violence and stalking.

### ISSUE THREAD

**Issue by AdaRoseCannon** [w3c/PWETF#69]
Many women have dealt with stalkers or may have a history with sexual violence. Avoid bringing up topics like this as it may...

**Comment by vlevantovsky** [comment]
I agree that shining a light on this sensitive subject is important but I am not sure I am comfortable with the language added to address it. Making strong statements may be seen as an implication that different forms of violence (sexual violence in particular) are widespread, and I am also puzzled by this particular statement: "In the course of our work we may have to discuss these important issues ..." - what prompted it?

**Comment by AdaRoseCannon** [comment]
Re the language, could you raise the issue in the PR itself.

Unfortunately these forms of violence are widespread, on two separate instances at TPAC I saw stalking being brought up without much thought, and it being not related to the topic at hand so much, shortly followed by another person in the room commenting how they were currently dealing with an active stalker at the time and perhaps it shouldn't be brought up so lightly.

These both resulted in embarrassment for the person putting their foot-in-mouth and they swiftly apologised but it is definitely something which can go a lot worse.

In our work we should discuss these issues due to the way the technology we enable can be used to enable stalking and harassment, but it is important to do so carefully.
