### ISSUE TITLE
In case it is of use as a referent or example for the CEPC work...

### ISSUE THREAD

**Issue by koalie** [w3c/PWETF#70]
Via David Singer: [ISO Code of Conduct for the technical work](https://www.iso.org/files/live/sites/isoorg/files/store/en/PUB100397.pdf) (PDF)

**Comment by TzviyaSiegman** [comment]
Thank you. I added this to [References and Resources](https://github.com/w3c/PWETF/blob/master/ReferencesAndResources.md)
