### ISSUE TITLE
Reporting section edits

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/PWETF#84]
comment by @jeffjaffe:

talking about Chairs, we first say that they can raise issues with ombuds, then we say (in a separate paragraph) that they may take action.  
Recommended changes:
* Chairs are *expected *to deal with issues in their groups when they can but may ask for help from ombuds. 
* Combine paragraphs

note from tzviya: much of the infrastructure for reporting is not in place yet, so this section is expected to be edited in the future.

**Comment by jeffjaffe** [comment]
See #90
