### ISSUE TITLE
Positive first

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/PWETF#86]
The draft CEPC includes a list of unacceptable behaviours, followed by a list of expected behaviours. I think it should take a more positive orientation and provide the expected behaviours first, followed by a list of problematic ones which, I hope, come across as just details of failures to meet the expected behaviours.

**Comment by wseltzer** [comment]
As this is a document meant to represent W3C, I feel strongly that it should start with the expected behavior.

**Comment by plehegar** [comment]
imho, while this is just moving text around, this issue ought to be addressed before moving forward, the label CEPC-editorial.

**Comment by TzviyaSiegman** [comment]
We agreed to re-order text (positive first) in our [last meeting](https://www.w3.org/2020/01/09-pwe-minutes.html#item02). @plehegar I am not sure I understand your comment. Would you please clarify?

**Comment by plehegar** [comment]
@TzviyaSiegman , I only meant to highlight the importance of this issue even if the change was editional. I'm happy with decision to do the re-ordering.

**Comment by TzviyaSiegman** [comment]
thanks. See #110
