### ISSUE TITLE
Clarify bullying and retaliation

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/PWETF#89]
I think the draft CEPC is not comprehensive enough on the issues of bullying and retaliation (which I'm linking here though they may be separable). I think a better definition is needed about what constitutes bullying, including acknowledging many different contexts for it (it's not just manager-to-employee or peer-to-peer for instance). Retaliation, which is often its own form of bullying, needs a definition and more references. I have seen in many environments how people can engage in bullying and retaliation in ways that toe but do not cross the line of formal policies, so I think this policy needs to better innoculate against that.

**Comment by TzviyaSiegman** [comment]
We have a definition of bullying in the glossary, and many of the unacceptable behaviors could be categorized as bullying. We would like to avoid a scenario in which someone feels they are being bullied, and the bully can point to a specific line in the CEPC to say they have not violated it.
 
+1 to clarifying retaliation.
